# Generated by Django 2.2.24 on 2022-07-28 23:35

from django.db import migrations


def update_new_building_in_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220729_0217'),
    ]

    operations = [migrations.RunPython(update_new_building_in_flat),
    ]
