# Generated by Django 2.2.24 on 2022-07-29 11:46

import phonenumbers
from django.db import migrations


def update_pure_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    if flat_set.exist():
        for flat in flat_set.iterator():
            try:
                phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            except Exception as e:
                print(f'got error while parsing phone number: {e}')
            
            if phonenumbers.is_valid_number(phone_number):
                flat.owner_pure_phone = phone_number
                flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [migrations.RunPython(update_pure_phone_numbers),
    ]
