# Generated by Django 2.2.24 on 2022-08-02 14:45

from django.db import migrations


def create_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220802_1552'),
    ]

    operations = [migrations.RunPython(create_owners),
    ]
